### ISSUE TITLE
Unable to make a payment; the page gets stuck in a "loop"

### ISSUE THREAD

**Issue by pepemiranda** [TipiCode/woocommerce-gateway-recurrente#1]
After the checkout when woocommerce is going to ask for the payment details the page keeps redirecting and it is not possible to make the payment.

Site specifications:
WordPress version: 5.8.3
WooCommerce version: 6.1.0
PHP version: 8.0.8
Other plugins activated: none
Theme: twenty-twenty-one

Screenshots:
<img width="997" alt="Captura de Pantalla 2022-01-12 a la(s) 16 55 30" src="https://user-images.githubusercontent.com/60155742/149236180-90c789e8-3b4b-4b8a-adeb-c57f02820f31.png">

Video: 
https://user-images.githubusercontent.com/60155742/149237418-5a7f4782-8cad-42a5-9fbc-52e30d848aef.mp4

Log:
[recurrente-2022-01-12-adf7e3a63c0128841f7c660eb9030ca3.log](https://github.com/TipiCode/woocommerce-gateway-recurrente/files/7858461/recurrente-2022-01-12-adf7e3a63c0128841f7c660eb9030ca3.log)

**Comment by jcromane** [comment]
Puede ser que el pago que estas introducciendo es muy bajo

**Comment by pepemiranda** [comment]
> Puede ser que el pago que estas introducciendo es muy bajo

¡Muchas gracias por el apoyo! Ese era el problema, ya pude hacer el pago sin ningún problema. Excelente plugin, ya era necesario 😁

**Comment by edguy369** [comment]
> > Puede ser que el pago que estas introducciendo es muy bajo
> 
> ¡Muchas gracias por el apoyo! Ese era el problema, ya pude hacer el pago sin ningún problema. Excelente plugin, ya era necesario 😁

Gracias por la resolución! Agregamos en la versión [v1.0.2](https://github.com/TipiCode/woocommerce-gateway-recurrente/releases/tag/v1.0.2) la opcion para logear los Http Response codes para mejorar la identificación de errores dentro del log, tambien agregamos una redirección al momento de un error hacia el Checkout para que no ocurra ese loop.
