### ISSUE TITLE
Problema al cobrar en dólares

### ISSUE THREAD

**Issue by jerryjmitchell** [TipiCode/woocommerce-gateway-recurrente#13]
Estimados buenos días, un gusto saludarlos nuevamente.

Escribo ya que tengo un inconveniente, el plugin funciona bien si cobro en quetzales, pero cuando quiero cobrar en dólares, me da error. Veo que en la configuración del plugin dice que la moneda del comercio es quetzales, pero resulta que el comercio con el que estoy probando, cobra en quetzales y también en dólares. Existe alguna forma de poder solucionar esto?

![image](https://github.com/TipiCode/Woocommerce-Recurrente/assets/10886643/545b3b7c-154a-4080-9e24-c5db58a0f1ba)

Saludos.

**Comment by edguy369** [comment]
Hola que tal! Que plugin o configuración estas utilizando para poder habilitar la función de multiples monedas.

**Comment by jerryjmitchell** [comment]
Muchas gracias por la respuesta. Estoy utilizando este:

![image](https://github.com/TipiCode/Woocommerce-Recurrente/assets/10886643/2d67b1ae-23fb-4bd2-8a32-3d173bb8aafc)

Eso es porque me permite poner precios en diferente moneda de manera manual y no a través de algún tipo de cambio. 

Saludos.

**Comment by edguy369** [comment]
Ok! Te comento que actualmente no soporta el plugin, pago multi moneda de esa manera ya que se basa en la moneda base de WooCommerce. Pero me parece una excelente observación para la siguiente versión, con tu permiso haremos pruebas con el plugin que estas utilizando.

**Comment by jerryjmitchell** [comment]
Muchas gracias por tu respuesta. 

Y hay algún plugin que si funcione para poder hacer el sitio multimoneda? No me importaría usar cualquiera con tal de que me funcione de esa manera.

Saludos.

**Comment by edguy369** [comment]
Hola! Perdon por la demora.

Actualmente no se a testeado con ningun plugin multimoneda, desafortunadamente la funcionalidad se a previsto unicamente con la moneda base de WooCommerce.

Saludos!

**Comment by edguy369** [comment]
Hola!

Me comentan que podrias probar con la verisión 1.0.5 esa versión cuenta con una manera experimental de obtener la moneda de tu sitio, puede que solucione tu inconveneinte.

Saludos!

**Comment by jerryjmitchell** [comment]
> Hola!
> 
> Me comentan que podrias probar con la verisión 1.0.5 esa versión cuenta con una manera experimental de obtener la moneda de tu sitio, puede que solucione tu inconveneinte.
> 
> Saludos!

Hola! Esto solventó el inconveniente, funcionó súper bien.

Muchas gracias!
