### ISSUE TITLE
Error de incompatibilidad con la característica HIGH-PERFOMANCE ORDER STORAGE

### ISSUE THREAD

**Issue by VivianRocio1996** [TipiCode/woocommerce-gateway-recurrente#14]
El mensaje de error específico es:
Este plugin es incompatible con la función ENABLE WOOCOMMERCE FEATURE HIGH-PERFORMANCE ORDER STORAGE. No debe estar activada.

Entorno:
   Tema: Hello Elementor:  [3.0.1] (Hello Elementor child)
    WordPress: [ 8.5.2]
    WooCommerce:  [6.4.3]
    Plugin de pasarela de pagos recurrentes: [1.1.0]
    
    El error se produjo al instalar el plugin por medio de zip.
    Capturas de pantalla:
    
![ERROR PLUGIN](https://github.com/TipiCode/Woocommerce-Recurrente/assets/110305435/10609851-249c-4d9d-b5ed-dd8255c867b5)
![critical error website](https://github.com/TipiCode/Woocommerce-Recurrente/assets/110305435/a03d49dd-d21f-42c7-aa1d-467c8c263c13)

== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: Percona Server (GPL), Release 23, Revision 500fcf5 v5.7.23-23
	PHP Version: 8.0.30
	PHP Memory Limit: 512M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 516M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.4.3
	Site URL: https://arvejamarketing.com
	Home URL: https://arvejamarketing.com
	WP Multisite: No
	Max Upload Size: 512 MB
	Memory limit: 40M
	Max Memory limit: 512M
	Permalink Structure: /%postname%/
	Language: es
	Timezone: -6
	Admin Email: f.godinez@bideadigital.com
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor Child
	Version: 1.0.1
	Author: Elementor Team
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 3.0.1
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: es_GT
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 3.19.2
		Author: Elementor.com

	Elementor Pro
		Version: 3.19.2
		Author: Elementor.com

	Head & Footer Code
		Version: 1.3.3
		Author: Aleksandar Urošević

	JetBlocks For Elementor
		Version: 1.3.10
		Author: Crocoblock

	JetBlog For Elementor
		Version: 2.3.6
		Author: Crocoblock

	JetElements For Elementor
		Version: 2.6.15
		Author: Crocoblock

	JetEngine
		Version: 3.3.6
		Author: Crocoblock

	JetMenu
		Version: 2.4.3
		Author: Crocoblock

	JetProductGallery
		Version: 2.1.14
		Author: Crocoblock

	JetSearch
		Version: 3.2.3
		Author: Crocoblock

	JetSmartFilters
		Version: 3.3.2
		Author: Crocoblock

	JetTabs For Elementor
		Version: 2.2.1
		Author: Crocoblock

	JetWooBuilder For Elementor
		Version: 2.1.10
		Author: Crocoblock

	Site Kit by Google
		Version: 1.120.0
		Author: Google

	The Bluehost Plugin
		Version: 3.8.4
		Author: Bluehost

	WooCommerce
		Version: 8.6.1
		Author: Automattic

	WP Rocket
		Version: 3.15.9
		Author: WP Media

== Must-Use Plugins ==
	Endurance Page Cache
		Version: 2.2
		Author: Mike Hansen

	SSO
		Version: 0.4
		Author: Garth Mortensen, Mike Hansen

== Uso de los elementos ==
	
	archive : 1
		heading : 1
		jet-ajax-search : 1
		posts : 1
	container : 2
		container : 2
		jet-login : 1
		jet-register : 1
	footer : 1
		button : 1
		heading : 3
		icon-list : 5
		image : 1
		nav-menu : 1
		social-icons : 1
		text-editor : 1
	header : 1
		container : 6
		icon : 1
		image : 1
		jet-blocks-cart : 1
		nav-menu : 1
	page : 1
		heading : 1
		icon-list : 1
		image : 2
	product : 1
		container : 10
		heading : 4
		jet-single-add-to-cart : 1
		jet-single-price : 1
		jet-woo-product-gallery-slider : 1
		jet-woo-products : 1
		text-editor : 2
	section : 6
		heading : 3
		image : 7
		jet-images-layout : 4
	wp-page : 10
		animated-headline : 1
		button : 23
		container : 3
		heading : 69
		icon-list : 10
		image : 42
		image-box : 5
		image-gallery : 1
		jet-ajax-search : 1
		jet-brands : 1
		jet-engine-booking-form : 1
		jet-testimonials : 1
		menu-anchor : 1
		posts : 1
		social-icons : 1
		text-editor : 18
		wc-elements : 3
	single-post : 1
		heading : 2
		image : 1
		jet-posts : 1
		post-info : 1
		post-navigation : 1
		theme-post-content : 1
	product-archive : 2
		container : 8
		heading : 3
		jet-smart-filters-pagination : 1
		jet-smart-filters-radio : 1
		jet-smart-filters-select : 1
		jet-woo-products : 1
	jet-woo-builder-thankyou : 0
		container : 7
		heading : 4
		jet-thankyou-customer-address-details : 1
		jet-thankyou-order : 1
		jet-thankyou-order-details : 1
	jet-woo-builder-myaccount : 0
		container : 19
		heading : 2
		jet-custom-menu : 1
		jet-myaccount-account-details : 1
		jet-myaccount-addresses : 1
		jet-myaccount-content : 1
		jet-myaccount-dashboard : 1
		jet-myaccount-downloads : 1
		jet-myaccount-order : 1
		jet-switcher : 1
	jet-woo-builder-checkout : 0
		container : 11
		heading : 4
		jet-checkout-billing : 1
		jet-checkout-coupon-form : 1
		jet-checkout-login-form : 1
		jet-checkout-order-review : 1
		jet-checkout-payment : 1
	jet-woo-builder-cart : 0
		button : 1
		container : 9
		heading : 2
		jet-cart-empty-message : 1
		jet-cart-table : 1
		jet-cart-totals : 1
	jet-woo-builder : 13
		container : 10
		heading : 4
		jet-single-add-to-cart : 1
		jet-single-price : 1
		jet-woo-product-gallery-slider : 1
		jet-woo-products : 1
		text-editor : 2

== Ajustes ==
	
	cpt_support: post, page, jet-menu, jet-woo-builder
	allow_tracking: yes
	unfiltered_files_upload: 1

== Features ==
	Custom Fonts: 0
	Custom Icons: 0

== Integrations ==
	
	woocommerce: Active

== Experimentos de Elementor ==
	Carga de recursos mejorada: Activo por defecto
	Carga de CSS mejorada: Activo por defecto
	Fuentes de iconos integradas: Inactivo por defecto
	Puntos de ruptura personalizados adicionales: Activo por defecto
	admin_menu_rearrangement: Inactivo por defecto
	Contenedor Flexbox: Activo
	Actualizar la librería Swiper: Inactivo por defecto
	Contenedor Grid: Activo
	Default to New Theme Builder: Activo por defecto
	Encabezado y pie de página del tema Hello: Activo por defecto
	Barra superior del editor: Inactivo por defecto
	Optimized Gutenberg Loading: Activo por defecto
	Build with AI: Activo por defecto
	Páginas de destino: Activo por defecto
	Elementos anidados: Inactivo por defecto
	Carga diferida de imágenes de fondo: Inactivo por defecto
	Optimize Image Loading: Activo por defecto
	Guía de estilo global: Activo por defecto
	Page Transitions: Activo
	Notes: Activo por defecto
	Display Conditions: Inactivo por defecto
	Form Submissions: Activo por defecto
	Scroll Snap: Activo por defecto
	Menu: Inactivo por defecto
	Taxonomy Filter: Inactivo por defecto

**Comment by edguy369** [comment]
Hola muchas gracias por el reporte! Ya se esta replicando para poderte brindar una solución

**Comment by Awasto** [comment]
Hola que tal, ya está disponible la nueva versión, por favor descargar esa versión; acá dejo el link para que la puedas configurar https://blog.codingtipi.com/como-aceptar-pagos-con-tarjeta-desde-woocommerce-con-recurrente/
