### ISSUE TITLE
versiones wordpress and woocommerce?

### ISSUE THREAD

**Issue by marcosmateom** [TipiCode/woocommerce-gateway-recurrente#15]
Hay planes para soportar las nuevas versiones de wordpress y WooCommerce?

Actualmente wordpress se encuentra en la version "6.4.3" y Woocommerce en la version "8.6.0".
La ultima version de Woocommerce-Recurrente  no soporeta ninguno de los 2 (segun mis pruebas. en las que probe regresar a las versiones soportadas cada una por separado y luego las 2 al mismo tiempo en cual caso si funciona).

En corto mi pregunta es si se tienen planes de continuar actualizando el plugin?

**Comment by edguy369** [comment]
Hola que tal!

Estamos en proceso de pruebas con una versión más estable para nuevas versiones de Wordpress y WooCommerce.

Esperamos poderla tener lista entre esta semana y la otra! Por favor mantente pendiente del repositorio.

**Comment by Awasto** [comment]
Hola que tal, ya está disponible la nueva versión, descargar esa versión por favor; acá dejo adjunto el link para que pueda configurar la nueva versión: https://blog.codingtipi.com/como-aceptar-pagos-con-tarjeta-desde-woocommerce-con-recurrente/
