### ISSUE TITLE
No hay métodos de pago disponibles 

### ISSUE THREAD

**Issue by zamsoss** [TipiCode/woocommerce-gateway-recurrente#16]
Recientemente hice una instalación nueva de WordPress y WooCommerce. Ingrese las claves API pero no sé si es por la compatibilidad del plugin, que no me deja completar el pago.

Indica que no hay métodos de pago disponibles. 

Adicionalmente, hay un error de compatibilidad con el (Order data storage), no es compatible con el high-performance Order storage. 

WooCommerce 8.6.1
WordPress 6.4.3
Recurrente Plugin 1.1.0

**Comment by Awasto** [comment]
Hola que tal, buen día; ya está disponible la nueva versión, por favor descargar esa versión, adicional dejo un link para configurar la nueva versión: https://blog.codingtipi.com/como-aceptar-pagos-con-tarjeta-desde-woocommerce-con-recurrente/
