### ISSUE TITLE
La ultima version del plugin no cambia el estado de la venta a "Completado"

### ISSUE THREAD

**Issue by JPaulMora** [TipiCode/woocommerce-gateway-recurrente#22]
**Describe the bug**

**To Reproduce**
1. Instalar plugin desde zip de master
2. Crear cuenta y asignar API keys
3. Crear un pedido
4. El cobro se hace pero la orden no pasa de estado

**Expected behavior**
La orden deberia ser completada

**Screenshots**
![image](https://github.com/TipiCode/Woocommerce-Recurrente/assets/8335656/1a461b52-b3f7-4527-98a6-fe84cffdd057)
Los pedidos cancelados se han cambiado por "falta de pago"

![image](https://github.com/TipiCode/Woocommerce-Recurrente/assets/8335656/71d8f855-1502-4cd6-a91d-cefc00006586)

**Comment by Awasto** [comment]
Buen día

Acá te dejo un blog con el que te puedes guiar para resolver tu duda; el problema que tienes es debido a que no tienes configurado el paso 4 que aparece en el blog

Espero te ayude y que tengas buen día :D

https://blog.codingtipi.com/como-aceptar-pagos-con-tarjeta-desde-woocommerce-con-recurrente/

**Comment by JPaulMora** [comment]
Confirmo que este era el problema.
