### ISSUE TITLE
Producto inválido

### ISSUE THREAD

**Issue by zamsoss** [TipiCode/woocommerce-gateway-recurrente#23]
Producto Inválido

Estoy tratando de integrar Recurrente en una plataforma pero me indica error COD. 500-2 'Producto Invalido'

He tratado de leer si hay algo en la documentación pero no he encontrado nada

Wordpress Versión: 6.6.1
Woocommerce: 9.1.4 
Woocommerce Recurrente intregración: Versión 2.0.2

![image](https://github.com/user-attachments/assets/c845f441-8e01-4eb4-ac47-f3b1b62b1f9d)

**Comment by wmsales** [comment]
¿Has logrado resolver el problema?

**Comment by edguy369** [comment]
Hola! 

Este error se debe a dos posibles factores:

1. El producto es menos a 5Q o 5$ que es el minimo que permite Recurrente.
2. La cuenta de Recurrente aún se encuentra en revisión por lo cual existe un tope en cada transacción.
