### ISSUE TITLE
"Recurrente Complete" después del pago. (Se necesita status "Recurrente Processing")

### ISSUE THREAD

**Issue by chanderdiaz** [TipiCode/woocommerce-gateway-recurrente#24]
**Describe the bug**
Cuando un cliente paga su pedido con Recurrente, le cambia el status a "Recurrente Complete" y envía los respectivos correos al cliente de "Pedido completado" cuando el pedido está recien creado y debería de tener un status de "Recurrente Processing" y enviar correo de pedido en proceso. 

**Screenshots**
![image](https://github.com/user-attachments/assets/9bf7b85a-593c-4931-be8e-54fcb2b347cf)

**Versiones:**
 - WordPress: 6.6.1
 - WooCommerce: 9.1.2
 - Recurrente: 1.0.5

**Comment by edguy369** [comment]
Porfavor actualiza a la nueva versión del plugin, aqui se encuentra solucionado este error.
