### ISSUE TITLE
No cambia el estado de pedido despues de pagar

### ISSUE THREAD

**Issue by bigson791** [TipiCode/woocommerce-gateway-recurrente#26]
Al finalizar el pago del pedido, no se cambia el estado  a procesando 

![recurrente](https://github.com/user-attachments/assets/a140e95d-3ab2-4af7-8954-37ce5d636b1d)

Esto ocurre en: 
Wordpress 6.6.2
WooCommerce 9.3.2

**Comment by edguy369** [comment]
Hola que tal buenos dias! 

Comprendo! Parece que el Webhook no esta configurado correctamente, porfavor revisa la guía oficial en el siguiente enlace, seria el punto número 4

https://blog.codingtipi.com/como-aceptar-pagos-con-tarjeta-desde-woocommerce-con-recurrente/

**Comment by bigson791** [comment]
Efectivamente, se debe confirgurar el paso 4, muchas gracias.
