### ISSUE TITLE
Version minima del plugin es PHP 8.0

### ISSUE THREAD

**Issue by JPaulMora** [TipiCode/woocommerce-gateway-recurrente#4]
<img width="638" alt="image" src="https://user-images.githubusercontent.com/8335656/152553092-2f019de7-70e7-49f0-beab-0dc6df24b484.png">

Algunos sites no han sido actualizados a PHP 8.0 por incompatibilidad de plugins. 

Gracias

**Comment by edguy369** [comment]
Hola! @JPaulMora gracias por tu comment. 
Se añadio soporte testeado para php 7.2 o superior en la versión del plugin 1.0.4, puedes encontrar la ultima versión en el siguiente link :  https://github.com/TipiCode/woocommerce-gateway-recurrente/releases/tag/v1.0.4
