### ISSUE TITLE
productos de la página en dólares(USD), pero cobro quetzales(GTQ)

### ISSUE THREAD

**Issue by bigson791** [TipiCode/woocommerce-gateway-recurrente#5]
Hola, tengo una pagina con precios en quetzales y dólares, al momento de finalizar la compra en recurrente, lo cobra en quetzales, ayuda por favor.
![total de los productos](https://user-images.githubusercontent.com/30543678/152852351-d8f79efd-9884-4ac5-8508-be1ebb33c40a.JPG)
![cobro en recurrente](https://user-images.githubusercontent.com/30543678/152852524-0e00765b-36cf-4f3b-b10a-ca5b47c6f3c1.JPG)

**Comment by edguy369** [comment]
Hola! @bigson791 que tal, que versión del plugin tienes? por favor actualiza a la última y verifica nuevamente con una prueba el cobro 
Ultima versión : https://github.com/TipiCode/woocommerce-gateway-recurrente/releases/tag/v1.0.4

**Comment by bigson791** [comment]
actualice a la version 1.0.4, pero continua este inconveniente
![total de los productos](https://user-images.githubusercontent.com/30543678/152860706-32e7cf66-a70f-4ddf-a240-88b2498f44e2.JPG)
![cobro en recurrente](https://user-images.githubusercontent.com/30543678/152860732-d7e5645d-9212-424c-940d-db570eea1e59.JPG)

**Comment by jose10josh** [comment]
Hola @bigson791 ! ¿Podrías confirmar que si tienes dólares estadounidenses en la moneda de Woocommerce? 
![image](https://user-images.githubusercontent.com/64654086/152866422-0468341b-3534-4615-ba6a-45febed6f9e1.png)

**Comment by bigson791** [comment]
Tengo dos monedas, GTQ y USD

**Comment by bigson791** [comment]
Está es la página[https://floresadomicilioGuatemala.com](url)

**Comment by edguy369** [comment]
@bigson791 Nos podrias brindar información de como estas manejando el multicurrency porfavor, que plugin estas utilizando, su versión, versión de wordpress, versión de Woocommerce, y de php, para poder replicar el inconveniente. Gracias!

**Comment by bigson791** [comment]
Claro, el plugin es WOOCS – Currency Switcher for WooCommerce

Versión 1.3.7.5

WordPress. 5.9

Woocommerce 6.1.1

PHP 7.3.33

**Comment by jose10josh** [comment]
Hola! @bigson791  
Se añadió soporte para el cambio de moneda, por le momento el portal de Recurrente soporta únicamente "GTQ" y "USD" puedes encontrar la ultima versión en este link: https://github.com/TipiCode/woocommerce-gateway-recurrente/releases/tag/v1.0.5
