### ISSUE TITLE
Clientes nuevos no pueden hacer compras

### ISSUE THREAD

**Issue by jerryjmitchell** [TipiCode/woocommerce-gateway-recurrente#6]
Buenos días!

Tengo un problema, ya que varios clientes me han reportado que no pueden hacer pagos, estuve investigando, y encontré cuál es el problema:

Cuando un cliente nuevo quiere hacer un pago, hace todo el proceso, ingresa sus datos, da click en pagar, y luego la página se queda en un loop con un círculo, en la parte superior del explorador, aparece un mensaje que dice que tiene que habilitar las ventanas emergentes, el cliente da que si las acepta, pero luego de esto no pasa nada, entonces el cliente nuevamente tiene que buscar los productos y hacer el pedido, pero esto provoca que los clientes muchas veces no compren.

Video del inconveniente:
https://user-images.githubusercontent.com/10886643/182630957-16b975cd-3c40-48c9-94de-32da69fd0a12.mp4

Esto ha pasado con varios clientes, yo repliqué el error en una instalación nueva de Chrome sin ningún tipo de bloqueador de anuncios o extensiones de terceros.

Habrá alguna forma de que por ejemplo al momento de hacer el checkout los datos de la tarjeta se puedan ingresar directamente desde la página web?

Saludos.

**Comment by jcromane** [comment]
Actualiza tu woocommerce, wordpress a la ultima versión y si no lo arregla, actualiza tu tema de wordpress, eso arregla lo de la ventana emergente y lo hace desde la misma del checkout

**Comment by jerryjmitchell** [comment]
Buenas noches, muchas gracias por tu respuesta. Te comento que hice las actualizaciones que me dijiste, y cuando le doy pagar, me redirecciona a otra pestaña: 

![image](https://user-images.githubusercontent.com/10886643/183815669-a44724e5-eccc-4a73-83b0-91f5bb1143bf.png)

Voy a consultar con los clientes si se genera algún tipo de inconveniente relacionado al bloqueo de las ventanas emergentes.

Muchas gracias por tu respuesta.

**Comment by jerryjmitchell** [comment]
Te comento que sigo teniendo el inconveniente, ya todo está actualizado, pero aún así los clientes hacen el pedido, y se les bloquean las "ventanas emergentes", 

El pedido si se hace en woocommerce, pero a ellos no les aparece la pantalla para poder realizar el pago.

![image](https://user-images.githubusercontent.com/10886643/185210579-4062bf0d-6483-4780-ba4b-739b92fbef3d.png)

**Comment by jerryjmitchell** [comment]
Buenas tardes! Al final, encontré el problema de compatibilidad, y es con el plugin RankMath SEO, si yo tengo activado ese plugin, al momento de pagar, el explorador me dice que se tienen que habilitar las ventanas emergentes y pasa el problema que puse en el video de arriba, cuando desactivo el plugin, todo funciona sin ningún problema. Sería de revisar por qué es que pasa esto específicamente con este plugin.

**Comment by edguy369** [comment]
> Buenas tardes! Al final, encontré el problema de compatibilidad, y es con el plugin RankMath SEO, si yo tengo activado ese plugin, al momento de pagar, el explorador me dice que se tienen que habilitar las ventanas emergentes y pasa el problema que puse en el video de arriba, cuando desactivo el plugin, todo funciona sin ningún problema. Sería de revisar por qué es que pasa esto específicamente con este plugin.

Que tal buenas tardes! Podrias brindarnos la version que tienes instalada del plugin RankMatch SEO porfavor, Gracias por apoyarnos en encontrar el problema de compatibilidad!

**Comment by jerryjmitchell** [comment]
> > Buenas tardes! Al final, encontré el problema de compatibilidad, y es con el plugin RankMath SEO, si yo tengo activado ese plugin, al momento de pagar, el explorador me dice que se tienen que habilitar las ventanas emergentes y pasa el problema que puse en el video de arriba, cuando desactivo el plugin, todo funciona sin ningún problema. Sería de revisar por qué es que pasa esto específicamente con este plugin.
> 
> Que tal buenas tardes! Podrias brindarnos la version que tienes instalada del plugin RankMatch SEO porfavor, Gracias por apoyarnos en encontrar el problema de compatibilidad!

Claro que sí, la versión que tengo instalada actualmente es la Versión 1.0.97. Probé en 4 sitios diferentes y en todos cuando desactivo el plugin RankMath, todo funciona bien, y cuando lo habilito, el mensaje aparece nuevamente.

El problema que tengo ahora, es que no puedo activar ese plugin si quiero tener el plugin de cobro con tarjeta, pero espero se pueda solucionar.

Saludos.

**Comment by edguy369** [comment]
> > > Buenas tardes! Al final, encontré el problema de compatibilidad, y es con el plugin RankMath SEO, si yo tengo activado ese plugin, al momento de pagar, el explorador me dice que se tienen que habilitar las ventanas emergentes y pasa el problema que puse en el video de arriba, cuando desactivo el plugin, todo funciona sin ningún problema. Sería de revisar por qué es que pasa esto específicamente con este plugin.
> > 
> > 
> > Que tal buenas tardes! Podrias brindarnos la version que tienes instalada del plugin RankMatch SEO porfavor, Gracias por apoyarnos en encontrar el problema de compatibilidad!
> 
> Claro que sí, la versión que tengo instalada actualmente es la Versión 1.0.97. Probé en 4 sitios diferentes y en todos cuando desactivo el plugin RankMath, todo funciona bien, y cuando lo habilito, el mensaje aparece nuevamente.
> 
> El problema que tengo ahora, es que no puedo activar ese plugin si quiero tener el plugin de cobro con tarjeta, pero espero se pueda solucionar.
> 
> Saludos.

Buen dia! 

Con gusto vamos a recrear el inconveniente, para buscarle una solución! De igual manera si cuentas con conocimientos de desarrollo para wordpress o conoces de alguien eres bienvenido a contribuir en los plugins de uso libre que puedas necesitar para tus sitios. 

Saludos!

**Comment by jerryjmitchell** [comment]
Muchas gracias Ed! Te comento que no soy programador, pero, quería saber de qué forma te puedo contactar? Ya que tengo una consulta fuera de este plugin y es relacionado a otro. Muchas gracias!

**Comment by edguy369** [comment]
> Muchas gracias Ed! Te comento que no soy programador, pero, quería saber de qué forma te puedo contactar? Ya que tengo una consulta fuera de este plugin y es relacionado a otro. Muchas gracias!

Con mucho gusto nos puedes seguir en nuestra cuenta oficial de twitter o instagram y enviarnos un mensaje por esos canales. o al correo root@codingtipi.com

**Comment by zerod696** [comment]
Hola, quisiera reportar que el error sigue ocurriendo incluso sin tener el plugin de RankMath SEO instalado.
Tengo alrededor de 20 plugins activos en este sitio por lo que aun no he intentado cual esta dando conflicto.
Para SEO tengo Yoast SEO activo, 

![Error carga de pagina](https://user-images.githubusercontent.com/120614853/207763296-c3dea7ee-5655-4cd1-9232-8029f3e9b699.jpg)

**Comment by edguy369** [comment]
> Hola, quisiera reportar que el error sigue ocurriendo incluso sin tener el plugin de RankMath SEO instalado. Tengo alrededor de 20 plugins activos en este sitio por lo que aun no he intentado cual esta dando conflicto. Para SEO tengo Yoast SEO activo,
> 
> ![Error carga de pagina](https://user-images.githubusercontent.com/120614853/207763296-c3dea7ee-5655-4cd1-9232-8029f3e9b699.jpg)

Hola! Gracias por el reporte, podrias intentar desactivando algunos plugins solo para tener como referencia el plugin que tambien puede causar este inconveniente.

**Comment by zerod696** [comment]
> 

Hola!! el plug in que genero el conflicto fue el **YOAST SEO Versión 19.12.**

Seria de muchisima utilidad si nos recomiendan pasos a seguir ya que los sitios se podrian ver afectados al desactivar el SEO 
Tengo Versión 6.1.1 de WP y Versión 7.2.0 de WooCommerce

**Comment by Awasto** [comment]
Hola que tal, la nueva versión ya está disponible con el arreglo al problema, descargar esa por favor; acá dejo el link para poder configurarla: https://blog.codingtipi.com/como-aceptar-pagos-con-tarjeta-desde-woocommerce-con-recurrente/
