### ISSUE TITLE
Woocommerce Plugin

### ISSUE THREAD

**Issue by isafortuny** [TipiCode/woocommerce-gateway-recurrente#7]
Tengo el problema que al realizar la integración del procesador de pagos Recurrente y hacer un pedido de prueba, el pedido queda registrado en el backend (Woocommerce > Pedidos) pero no redirige al formulario de pago. 
¿Podrían apoyarme en cómo resolver este problema? 
Muchas gracias

**Comment by gitdelrafa** [comment]
Tengo el mismo problema ¿lo solucionaste?

**Comment by Awasto** [comment]
Hola buen día, ya está disponible la nueva versión en la cual ya está resuelto el problema, descargar esa versión por favor; acá dejo el link para que puedan configurarlo: https://blog.codingtipi.com/como-aceptar-pagos-con-tarjeta-desde-woocommerce-con-recurrente/
